/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@elegant-router/types";

export const layouts: Record<RouteLayoutKey, RawRouteComponent> = {
  base: () => import("@/layouts/base.vue"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  404: () => import("@/views/(builtin)/404/index.vue"),
  Home: () => import("@/views/home/index.vue"),
};
