/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteKey, RoutePathMap } from '@elegant-router/types';

const routePathMap: RoutePathMap = {
  "Root": "/",
  "NotFound": "/:pathMatch(.*)*",
  "404": "/404",
  "Home": "/home",
};

export function getRoutePath(key: RouteKey) {
  return routePathMap[key];
}
