/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const LocalSvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"icon-forbidden" | "icon-not-found" | "icon-server-error">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"icon-forbidden" | "icon-not-found" | "icon-server-error">;
          default: string;
          required: true;
      };
  }>>, {
      name: "icon-forbidden" | "icon-not-found" | "icon-server-error";
  }>;
  export const svgNames: ["icon-forbidden", "icon-not-found", "icon-server-error"];
  export type SvgName = "icon-forbidden" | "icon-not-found" | "icon-server-error";
  export default LocalSvgIcon;
}
